version: "3"
services:
  web:
    build: .
    ports:
      - "8081:80"
    volumes:
      - ./appsettings.json:/app/appsettings.json
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
    depends_on:
      - db
  db:
    image: "mysql:5.7"
    restart: always
    volumes:
      - ./todo.sql:/docker-entrypoint-initdb.d/todo.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
